#!/usr/bin/env python
import telepot
import sys
bot = telepot.Bot('---------------------------------------------------')
from pprint import pprint
#response = bot.getUpdates()
#pprint(response)
f = open(sys.argv[1],'r')
message = f.readlines()
group = 0
bot.sendMessage(group,'\n'.join(message))
